name: GreenSky
version: '${version}'
main: com.greencodes.greensky.GreenSkyPlugin
api-version: '26.1'
description: SkyBlock RPG vivo, explorável e social.
authors: [GreenCodes]

commands:
  island:
    description: Gerencia a sua ilha
    usage: /<command> <create|home|info|add|remove>
    aliases: [is]

permissions:
  greensky.admin:
    description: Comandos administrativos do GreenSky
    default: op
